version: '3.7'

networks:                        
  postgres_network:                 


services:
  test:
    container_name: test
    build:
      context: . 
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_PORT: ${DB_PORT} 
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}  
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    depends_on:
      - test-db
    networks:                             
      - postgres_network                    


  test-db:
    container_name: test-db
    image: postgres:12.5-alpine
    volumes:
      - psql-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 8991:${DB_PORT}
    restart: on-failure
    networks:
      - postgres_network
volumes:
  psql-db-data:
