version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.32-oracle:alpine
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_DOCKER_PORT:$MYSQL_DOCKER_PORT
    networks:                             
      - test-network
    volumes:
      - db_data:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    volumes:
      - .:/usr/src/app
    networks:                             
      - test-network

    #command: sh -c "npm install && npm run dev"

volumes:
  db_data:

networks:                        
  test-network:      
    driver: bridge