version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_DOCKER_PORT:$MYSQL_DOCKER_PORT
    networks:                             
      - test-network
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    volumes:
      - .:/usr/src/app
    networks:                             
      - test-network

    #command: sh -c "npm install && npm run dev"

volumes:
  db:
    driver: local

networks:                        
  test-network:      
    driver: bridge