version: '3.8'

networks:
  pledge_network:
    driver: bridge

services:
  # pledge:
  #   container_name: pledge
  #   build: .
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     PORT: ${NODE_PORT}
  #     DB_PORT: ${DB_PORT}
  #     DB_HOST: ${DB_HOST}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #   env_file:
  #     - .env
  #   ports:
  #     - ${NODE_PORT}:${NODE_PORT}
  #   expose:
  #     - ${NODE_PORT}
  #   volumes:
  #     - ./:/usr/src/app
  #   command: npm run start:dev
  #   depends_on:
  #     - host-db
  #   networks:
  #     - pledge_network

  host-db:
    container_name: host-db
    image: postgres:15
    volumes:
       - postgres-db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: on-failure
    networks:
      - pledge_network

volumes:
    postgres-db-volume:
        driver: local
        